apiVersion: v1
kind: PersistentVolume
metadata:
  name: app-pv
spec:
  storageClassName: local-path
  persistentVolumeReclaimPolicy: Retain
  capacity:
    storage: 10Gi
  accessModes:
  - ReadWriteMany
  hostPath:
    path: /Users/klim/Projects/everything-k8s/app
  
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: app-pvc
spec:
  volumeName: app-pv
  storageClassName: local-path
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 10Gi

# apiVersion: v1
# kind: Pod
# metadata:
#   name: test-vol
#   labels:
#     name: test-vol
# spec:
#   containers:
#   - name: app
#     image: busybox
#     command: ['sh', '-c', 'echo "The local volume is mounted!" > /data/test.txt']
#     volumeMounts:
#       - name: local-persistent-storage
#         mountPath: /data
#   volumes:
#     - name: local-persistent-storage
#       persistentVolumeClaim:
#         claimName: test-pvc