volumes:
  persistence: false

affinity:
  anti_affinity: false

components:
  autorecovery: false
  pulsar_manager: false
  toolset: true

kube-prometheus-stack:
  enabled: false
  prometheusOperator:
    enabled: false
  grafana:
    enabled: false
  alertmanager:
    enabled: false
  prometheus:
    enabled: false

zookeeper:
  replicaCount: 1
  podMonitor:
    enabled: false
  resources:
    requests:
      memory: 128Mi
      cpu: 0.075

bookkeeper:
  replicaCount: 1
  podMonitor:
    enabled: false
  resources:
    requests:
      memory: 512Mi
      cpu: 0.1

autorecovery:
  podMonitor:
    enabled: false

broker:
  replicaCount: 2
  podMonitor:
    enabled: false
  resources:
    requests:
      memory: 2Gi
      cpu: 0.25
  configData:
    autoSkipNonRecoverableData: 'true'
    # managedLedgerDefaultEnsembleSize: "1"
    # managedLedgerDefaultWriteQuorum: "1"
    # managedLedgerDefaultAckQuorum: "1"

proxy:
  replicaCount: 1
  podMonitor:
    enabled: false
  resources:
    requests:
      memory: 128Mi
      cpu: 0.1
  ingress:
    enabled: true
